# примеры API-запросов
#USER Authorization: Token 77079bb60a0ae24b0403d9f840039de68ccad88c
#ADMIN Authorization: Token 55eafdae7f87ed67070d279492f32f195df90a92
@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/add/
Content-Type: application/json
//Authorization: Token 77079bb60a0ae24b0403d9f840039de68ccad88c
//Authorization: Token 55eafdae7f87ed67070d279492f32f195df90a92


###

# создание объявления
POST {{baseUrl}}/add/
Content-Type: application/json

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/add/1/
Content-Type: application/json

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/add/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/add/?created_at_before=2020-10-01
Content-Type: application/json

###

# получение избранных объявлений
GET {{baseUrl}}/favorite/
Content-Type: application/json
//Authorization: Token 77079bb60a0ae24b0403d9f840039de68ccad88c
Authorization: Token 55eafdae7f87ed67070d279492f32f195df90a92

###

# создание избранного объявления
POST {{baseUrl}}/favorite/
Content-Type: application/json
//Authorization: Token 77079bb60a0ae24b0403d9f840039de68ccad88c
Authorization: Token 55eafdae7f87ed67070d279492f32f195df90a92

{
  "adv": 16
}