# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта +
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "помидор",
  "description": "Сочные"
}

###
# получение продуктов +
GET {{baseUrl}}/products/
Content-Type: application/json


###
# Получение продуктов постранично
GET {{baseUrl}}/products/?page=1
Content-Type: application/json


###
# обновление продукта +
PATCH {{baseUrl}}/products/4/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###
# удаление продукта +
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###
# поиск продуктов по названию и описанию +
GET {{baseUrl}}/products/?q=апе
Content-Type: application/json

###
# создание склада +
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Moscow, Red Square",
  "positions": [
    {
      "product": 2,
      "quantity": 150,
      "price": 220.50
    },
    {
      "product": 4,
      "quantity": 125,
      "price": 130
    }
  ]
}

###
# обновляем записи на складе +
PATCH {{baseUrl}}/stocks/4/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 243,
      "price": 145
    }
  ]
}

###
# поиск складов, где есть определенный продукт +
GET {{baseUrl}}/stocks/?products=4
Content-Type: application/json


###
# поиск складов, где есть определенный продукт (поиск через текст) +
GET {{baseUrl}}/stocks/?q=соч
Content-Type: application/json


###
# получение складов +
GET {{baseUrl}}/stocks/
Content-Type: application/json

###
# получение складов постранично
GET {{baseUrl}}/stocks/?page=1
Content-Type: application/json